### login
post http://localhost:4000/login
Content-Type: application/json

{
    "userName": "et",
    "password": "333"
}

### token kérés
post http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaSIsImlhdCI6MTY3Njc1Nzg5N30.HcxLe7gKFag5Tjk8lwN-4eOo3CAGBazffU8xKLTTSW8"
}

### logout
delete http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaSIsImlhdCI6MTY3Njc1NTI0M30.aS6yK0l548OjCU3irhz95vTLN2TuA9i4NFJsgXPBXqg"
}

### logout all
delete http://localhost:4000/logoutall
Content-Type: application/json


### Userek
get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaSIsImlhdCI6MTY3Njc1NDcwOCwiZXhwIjoxNjc2NzU1NjA4fQ.KYhG-su5z7jQJJzq9MYJr2J3lBnnPw6oZIjWRT4X6cs

### Egy user
get http://localhost:3000/users/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDMxNTE5NCwiZXhwIjoxNjQ0MzE4Nzk0fQ.q2ih8UiVs51Pa3UEc908O6tLt5Upl9NOlidEmQSksMQ

### User hozzáadása (regisztráció)
post http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "h",
    "lastName": "Fehér",
    "gender": "férfi",
    "userName": "h1",
    "email": "feher.h1@gmail.com",
    "password": "jozsi123",
    "number": 33333333
}

### User módosítása
put http://localhost:3000/users/14
Content-Type: application/json

{
    "firstName": "ULI",
    "lastName": "Buli",
    "gender": "férfi",
    "userName": "asd",
    "email": "balog.geza@gmail.com",
    "password": "123",
    "number": 123456
}

### Delete user
delete http://localhost:3000/users/17
### #endregion users

#--------------- get --------------- 
get http://localhost:3000/filmsForModal


### get films
get http://localhost:3000/films


### get tasks
get http://localhost:3000/tasks


### get person
get http://localhost:3000/persons


#--------------- get by id --------------

### get by id films
get http://localhost:3000/films/420

### get by id tasks
get http://localhost:3000/tasks/1339

### get by id persons
get http://localhost:3000/persons/0

#----------- delete ---------------

### delete by id films
delete http://localhost:3000/films/17

### delete by id tasks
delete http://localhost:3000/tasks/17

### delete by id persons
delete http://localhost:3000/persons/0

#------------ post ---------------

### post films 
post http://localhost:3000/films
Content-Type: application/json

{
    "title": "Elmentem a vásárba",
    "production": 1555,
    "length": 50,
    "presentation": "1555.02.02.",
    "youtube": 0

}

### post tasks 
post http://localhost:3000/tasks
Content-Type: application/json

{
    "filmid": "9999",
    "personid": "9292",
    "denomination": "rendező"

}

### post persons 
post http://localhost:3000/persons
Content-Type: application/json

{
    "name": "Mekk Elek",
    "gender": "férfi"

}


#------------- put ------------------

### put films by id
put http://localhost:3000/films/4
Content-Type: application/json

{
    "title": "Abalaba",
    "production": 123123,
    "length": 20,
    "presentation": "1351.03.10.",
    "youtube": 1


}

### put tasks by id
put http://localhost:3000/tasks/4
Content-Type: application/json

{
    "filmid": "1235",
    "personid": "3464",
    "denomination": "operatőr"


}

### put tasks by id
put http://localhost:3000/persons/0
Content-Type: application/json

{
    "name": "Mekk Elek meg egy",
    "gender": "férfi"
}

###-----------------------SZŰRÉS------------------------------------

get http://localhost:3000/getFilmFilter/a


### ----------------------------- USEREK-------------------------------------

### login
post http://localhost:4000/login
Content-Type: application/json

{
    "userName": "et",
    "password": "333"
}

### token kérés
post http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNkIiwiaWF0IjoxNjgxMTQ4OTE0fQ.cDecVERXm3NhonBZut-ymIQAaGPsV6sLyPn3XXI9s9Q"
}

### logout
delete http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNkIiwiaWF0IjoxNjgxMTQ4OTE0fQ.cDecVERXm3NhonBZut-ymIQAaGPsV6sLyPn3XXI9s9Q"
}

### logout all
delete http://localhost:4000/logoutall
Content-Type: application/json


### Userek
get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNkIiwiaWF0IjoxNjgxMTQ4OTE0fQ.cDecVERXm3NhonBZut-ymIQAaGPsV6sLyPn3XXI9s9Q

### Egy user
get http://localhost:3000/users/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNkIiwiaWF0IjoxNjgxMTQ4OTE0fQ.cDecVERXm3NhonBZut-ymIQAaGPsV6sLyPn3XXI9s9Q

### User hozzáadása (regisztráció)
post http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "asd",
    "lastName": "non22oo",
    "gender": "tunyacsap",
    "userName": "et",
    "email": "et@gmail.com",
    "password": "333",
    "number": 324
}

### User módosítása
put http://localhost:3000/users/1
Content-Type: application/json

{
    "firstName": "AKD",
    "lastName": "lkjasd",
    "gender": "fiu",
    "userName": "mu",
    "email": "mu@gmail.com",
    "password": "222",
    "number": 1234562
}

### Delete user
delete http://localhost:3000/users/17

### filmOfTaskForModal
get http://localhost:3000/filmOfTaskForModal/2

get a faszom
